### ISSUE TITLE
Documentation to implement SSR?

### ISSUE THREAD

**Issue by dabonde** [contentacms/contentajs#17]
Is there any documentation on implementing SSR with this? 

I've installed ContentaCMS and ContentaJS. ContentaJS is correctly proxying across to the cms api and returning responses but I receive failed GET requests if I attempt to request anything that's not an API request.

I'm sure there is a few more things to configure before I'll have working SSR with a react app but I haven't been able to find any documentation as to how the SSR works and how I can implement. Just that this supports it. 

Edit: I kind of realise now that I was thinking about this from the perspective of progressive decoupling. While Contenta and ContentaJS utilize a fully decoupled approach. Now that realise that it makes sense to me now that I would not getting any response via the ContentaJs proxy unless its an api call.

**Comment by e0ipso** [comment]
This project is not in charge of SSR, the documentation may be misleading. We'll work on making the documentation clearer.
