### ISSUE TITLE
NPM Script Missing in package.json - 'npm run stop'

### ISSUE THREAD

**Issue by jacksonrya** [contentacms/contentajs#21]
package.json is missing the script 'npm run stop' that would stop the pm2 process.

The [installation instructions](https://github.com/contentacms/contentajs/blob/master/docs/install.md#start-your-server) suggest this script exists. :)

**Comment by e0ipso** [comment]
Interesting. How would you imagine that works? Maybe `pm2 delete all`?

**Comment by jacksonrya** [comment]
I've been using `pm2 delete contentajs` to **kill the app** and it's current config, and then I use `pm2 stop contentajs` if I need to **pause** the processes for whatever reason, while keeping the current config.
I don't know the necessity of referencing the app name, but it could be added safety if others are running non-contentajs pm2 processes?

**Comment by e0ipso** [comment]
@jacksonrya I think I'm going to go with the `pm2` terminology, so it's clearer what the script is doing.
