### ISSUE TITLE
Connect to fresh drupal 8

### ISSUE THREAD

**Issue by rfnbnkr** [contentacms/contentajs#25]
I want use a fresh drupal 8 install with jsonapi module. are there any way to connect contentajs to fresh drupal 8?

**Comment by rfnbnkr** [comment]
Can you tell me which module required for work contentajs with contentacms?
i want try to connect with contentajs to drupal

**Comment by VincenzoGambino** [comment]
I haven't tried it yet but contenta uses https://www.drupal.org/project/contentajs to connect to contentajs.

**Comment by VincenzoGambino** [comment]
I have run a test with Minimal profile installation.
Download and enable [contentjs](https://www.drupal.org/project/contentajs) module for drupal along with all the required modules.
Enable permission JSON-RPC 2.0 for anonymous user (adjust the permission for your needs)
Enable cors in service.yml . You can copy the service.yml from contentacms and then adjust it for your needs.

Restart your contentajs instance _npm run restart_.

**Comment by e0ipso** [comment]
Thanks for the help provided @VincenzoGambino!

**Comment by e0ipso** [comment]
Any chance we can get PR to add this information to the documentation @VincenzoGambino?
