### ISSUE TITLE
Please define YOUR_PROJECT_NAME

### ISSUE THREAD

**Issue by ludo1960** [contentacms/contentajs#28]
Sorry to bother you guys, but I'm having issues installing contenta js. I have a folder mysite.com that serves up from mysite.com/web so in my nginx conf server name is mysite.com and server route is mysite.com/web. So when I move the contentajs folder to my PROJECT_NAME is that mysite.com or mysite.com/web or something else? When I move the contentajs to the mysite.com folder npm install returns no package json. Please tell me what folder YOUR_PROJECT_NAME is supposed to be.

Thanks in advance

**Comment by e0ipso** [comment]
This can be anything. For instance `mysite`.

**Comment by ludo1960** [comment]
Thanks for reply Mateu, the ever so helpful "create nodejs project first" should be emphasized on the install instructions! yes I know it is not a requirement, but any newbie wanting to get to grips with contenta would be mad not to install it. Thanks for your fine work, i'm having a great time playing with headless drupal. In fact I'm gonna write a getting to know contenta review from scratch to help other newbies.

**Comment by e0ipso** [comment]
Yeah, documentation is very hard. I would much appreciate if you could add those small details that matter documented in a PR.

Thanks for your kind words :-)

**Comment by ludo1960** [comment]
Hey Mateu,
Finished Part 1 of documentation, where to upload it? Also defined my project as /contenta and put content cms in /contenta/www then tried to install contentajs in /contenta, Needless to say it did not like this, come on give me a clue what goes where?
