### ISSUE TITLE
Installation troubles

### ISSUE THREAD

**Issue by ludo1960** [contentacms/contentajs#29]
Hello,
Trying to install contentajs, not sure what the project route is. I have a folder /contenta and I have contenta cms in the /contenta/www/ directory. I have installed contentajs in the /contenta/ directory but I get the following error:

root@aegir:/contenta# git init && git add . && git ci -m 'feat: project initialization with Contenta JS'
Reinitialized existing Git repository in /contenta/.git/
git: 'ci' is not a git command. See 'git --help'.

Did you mean one of these?
	am
	commit
	config
	diff
	fsck
	gc
	init
	mv
	rm

any ideas?

**Comment by e0ipso** [comment]
It's mean to say `commit`.
